apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
  namespace: default
spec:
  rules:
  # 1. API Subdomain -> Routes directly to Strapi Backend
  - host: api.marcel-avila.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-strapi
            port:
              number: 1337

  # 2. Main Domain -> Routes to Astro Frontend
  - host: marcel-avila.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-frontend-svc
            port:
              number: 80

# 3. AI Engine Subdomain -> Routes to AI Engine Backend
  - host: ai.marcel-avila.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ai-engine-svc
            port:
              number: 8000