name: Frontend CI Pipeline

on:
  push:
    branches: [ main ]
    paths: 
      - 'frontend/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths: 
      - 'frontend/**'
      - '.github/workflows/**'
  workflow_dispatch:
  repository_dispatch:
    types: [strapi-publish]

jobs:
  build-and-verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Converts the GitHub repository name to lowercase to satisfy Docker's strict naming rules
      - name: Set lowercase repository name
        run: |
          echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Local Image
        run: |
          docker build -t ghcr.io/${{ env.REPO_LC }}/portfolio-frontend:${{ github.sha }} ./frontend

      - name: Scan Image for Vulnerabilities (Trivy)
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
        with:
          image-ref: ghcr.io/${{ env.REPO_LC }}/portfolio-frontend:${{ github.sha }}
          format: 'table'
          exit-code: '1' 
          ignore-unfixed: true
          severity: 'CRITICAL'

      - name: Push Production Image
        # Only pushes the image if this is a merge into the main branch and new webhook dispatch events
        if: github.event_name == 'push' || github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch'
        run: |
          docker push ghcr.io/${{ env.REPO_LC }}/portfolio-frontend:${{ github.sha }}